#!/usr/bin/env bash
set -e

if ! type -p fzf >/dev/null; then
  echo "fzf not found on the system" >&2
  exit 1
fi

select_pr() {
  gh pr list --app dependabot --json number,author,title,statusCheckRollup | \
    jq -r '.[] | "#" + (.number|tostring) + " " + 
      if (.statusCheckRollup | all(.state == "SUCCESS" and .__typename == "StatusContext")) or
         (.statusCheckRollup | all(.conclusion == "SUCCESS" and .__typename == "CheckRun")) then
        "\u001b[32m"
      else
        "\u001b[31m"
      end +
      .title +
      "\u001b[0m"' | \
    fzf-tmux --ansi | \
    awk '{print $1}' | \
    sed -e 's/\#//'
  }

PR=$(select_pr)

if [ -z "${PR}" ]
then
  echo "No pull request selected"
else
  gh pr comment $PR -b "@dependabot merge"
fi

